# Generated by Django 3.1.7 on 2021-04-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210412_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('tech', 'Technology'), ('book', 'Books'), ('mov', 'Movies'), ('vGM', 'videoGames'), ('pcGM', 'pcGames'), ('ww', 'WomanWear'), ('mw', 'ManWear'), ('gw', 'girlWear'), ('bw', 'boyWear'), ('baw', 'babyWear')], max_length=20),
        ),
    ]
