# Generated by Django 3.1.7 on 2021-04-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210414_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Technology', 'Technology'), ('Books', 'Books'), ('Movies', 'Movies'), ('videoGames', 'videoGames'), ('pcGames', 'pcGames'), ('WomanWear', 'WomanWear'), ('ManWear', 'ManWear'), ('girlWear', 'girlWear'), ('boyWear', 'boyWear'), ('babyWear', 'babyWear')], max_length=20),
        ),
    ]
