# Generated by Django 3.1.7 on 2021-04-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210414_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order received', 'Order received'), ('Order shipped', 'Order shipped'), ('Order Delivered', 'Order Delivered')], max_length=50),
        ),
    ]
