# Generated by Django 3.1.7 on 2021-04-15 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='totalCost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='totalItemsCount',
            field=models.IntegerField(default=0),
        ),
    ]
