# Generated by Django 3.1.7 on 2021-04-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210415_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Beverage', 'Beverage'), ('Bakery', 'Bakery'), ('Supplement', 'Supplement'), ('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Shoes', 'Shoes'), ('Dress', 'Dress'), ('Watches', 'Watches'), ('Socks', 'Socks'), ('UnderWear', 'UnderWear'), ('Vroom', 'Vroom'), ('Camera', 'Camera'), ('Computer', 'Computer'), ('GameConsole', 'GameConsole')], max_length=20),
        ),
    ]
