# Generated by Django 3.1.7 on 2021-04-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='product',
            new_name='products',
        ),
    ]
