# Generated by Django 3.1.7 on 2021-04-16 18:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210416_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='orderHistoryID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
