# Generated by Django 3.1.7 on 2021-04-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210416_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='productID',
            new_name='productReviewID',
        ),
    ]
