# Generated by Django 3.1.7 on 2021-04-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210416_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopperreview',
            name='review',
            field=models.CharField(max_length=1000),
        ),
    ]
