# Generated by Django 3.1.7 on 2021-04-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210416_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='reviewScore',
            field=models.IntegerField(),
        ),
    ]
